package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@CrossOrigin
@Controller // This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

/*    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }*/

    @PostMapping// Map ONLY POST Requests
    public @ResponseBody UserModel addNewUser (@RequestBody UserRequest newUser) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        System.out.println(newUser.getName());

        UserModel n = new UserModel();
        n.setName(newUser.getName());
        n.setEmail(newUser.getEmail());
        UserModel retUser = userRepository.save(n);
        return retUser;
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<UserModel> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @DeleteMapping(path="")
    //can do multiples here...just separate with comma (i.e. @PathVariable("id"), @RequestParam()) etc
    public @ResponseBody String deleteUsers () {

        // This returns a JSON or XML with the users
        userRepository.deleteAll();
        return "all users successfully deleted";
    }

    @GetMapping(path="/bucky")
    public @ResponseBody String findBucky() {
        // This returns a JSON or XML with the users
        if ( userRepository.findByName("Bucky") != null) {
            return "We found bucky!";
        }
        else {
            return "Who the hell is bucky?";
        }

    }
}
